<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>heyitsleo/NFSTools</Authors>
    <Company>NFSTools</Company>
    <Description>Core library for processing VLT files - requires supplemental game modules</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>VaultLib.Core</PackageId>
    <Product>VaultLib.Core</Product>
    <TargetFramework>net9.0</TargetFramework>
    <Version>3.0.0-dev</Version>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSBuildGitHash" Version="2.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CoreLibraries\CoreLibraries.IO\CoreLibraries.IO.csproj" />
  </ItemGroup>

</Project>
